apiVersion: v1
items:
- apiVersion: image.openshift.io/v1
  kind: ImageStream
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-dev
      app.kubernetes.io/component: nodejs-dev
      app.kubernetes.io/instance: nodejs-dev
      app.kubernetes.io/name: nodejs
    name: nodejs-dev
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: build.openshift.io/v1
  kind: BuildConfig
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-dev
      app.kubernetes.io/component: nodejs-dev
      app.kubernetes.io/instance: nodejs-dev
      app.kubernetes.io/name: nodejs
    name: nodejs-dev
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: nodejs-dev:latest
    postCommit: {}
    resources: {}
    source:
      contextDir: nodejs-app
      git:
        ref: troubleshoot-review
        uri: https://github.com/vjustezgz/DO180-apps.git
      type: Git
    strategy:
      sourceStrategy:
        env:
        - name: npm_config_registry
          value: http://nexus-common.apps.eu46a.prod.ole.redhat.com/repository/npm-proxy
        from:
          kind: ImageStreamTag
          name: nodejs:12
          namespace: openshift
      type: Source
    triggers:
    - github:
        secret: uQshuXlPAkfPRhMEoXlO
      type: GitHub
    - generic:
        secret: KahkqV-Gw06iFFEaE-3X
      type: Generic
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    annotations:
      image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"nodejs-dev:latest"},"fieldPath":"spec.template.spec.containers[?(@.name==\"nodejs-dev\")].image"}]'
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-dev
      app.kubernetes.io/component: nodejs-dev
      app.kubernetes.io/instance: nodejs-dev
      app.kubernetes.io/name: nodejs
    name: nodejs-dev
  spec:
    replicas: 1
    selector:
      matchLabels:
        deployment: nodejs-dev
    strategy: {}
    template:
      metadata:
        annotations:
          openshift.io/generated-by: OpenShiftNewApp
        creationTimestamp: null
        labels:
          deployment: nodejs-dev
      spec:
        containers:
        - image: ' '
          name: nodejs-dev
          ports:
          - containerPort: 8080
            protocol: TCP
          resources: {}
  status: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      openshift.io/generated-by: OpenShiftNewApp
    creationTimestamp: null
    labels:
      app: nodejs-dev
      app.kubernetes.io/component: nodejs-dev
      app.kubernetes.io/instance: nodejs-dev
      app.kubernetes.io/name: nodejs
    name: nodejs-dev
  spec:
    ports:
    - name: 8080-tcp
      port: 8080
      protocol: TCP
      targetPort: 8080
    selector:
      deployment: nodejs-dev
  status:
    loadBalancer: {}
kind: List
metadata: {}
